services:
  ava:
    image: ava:latest
    build: ./ava
    container_name: ava
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: 1
    logging:
      driver: "json-file"
    env_file:
      - ./ava.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./instructions:/app/instructions"
    command: ["ava"]
    restart: unless-stopped
  tc:
    image: tc:latest
    build: ./tc
    container_name: tc
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - ./tc/.env
    command: ["tc"]
    restart: unless-stopped
