services:
  air:
    image: air:latest
    build: ./ava
    container_name: air
    environment:
      PYTHONUNBUFFERED: 1
    logging:
      driver: "json-file"
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/NASty/Documents/instructions:/instructions"
    command: ["air"]
    restart: unless-stopped
