FROM python:3.12-slim
WORKDIR /app
COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install --user -r requirements.txt
COPY ./dist/ava-2.3.1-py3-none-any.whl .
RUN pip install ava-2.3.1-py3-none-any.whl
