FROM python:3.12-slim
WORKDIR /app
COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install --user -r requirements.txt
COPY ./dist/ai_responder-1.2-py3-none-any.whl .
RUN pip install ai_responder-1.2-py3-none-any.whl
