[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "Ava"
description = "Generate responses for tickets coming in from Freshservice and leave ticket notes for next steps for agents."
version = "2.3.1"
requires-python = ">=3.12"

[project.scripts]
ava = "app.main:runner"
