import os, json
from openai import OpenAI

from app.ai import resolution_note_instructions, resolution_note_json
from app.sql.tickets import query_one_ticket
from app.freshservice.fs_resolution_note import put_resolution_note
from app.logs import logs

api_key = os.environ["OPENAIKEY"]
client = OpenAI(api_key=api_key)

def ai_resolution_note(ticket: dict) -> None:
    id = ticket.get("id")

    current_res_note = check_ticket(ticket)

    if current_res_note:
        logs("There appears to already be a note for this ticket, will have Ava reword the note better and repost.")
        content = current_res_note
    else:
        ticket = query_one_ticket(id)
        content = json.dumps(ticket, indent=4)

    ins = [{
        "role": "user",
        "content": content 
        }]

    logs(f"Ticket ID# {id} is now marked as CLOSED. Generating resolution note for ticket ID# {id}")
    
    response = client.responses.create(
            model="gpt-4o-mini",
            instructions=resolution_note_instructions,
            input=ins,
            text=resolution_note_json, 
            )

    if response:
        if response.output_text:
            resolution_note = response.output_text
            resolution_note = json.loads(resolution_note)
            resolution_note = resolution_note.get("resolution_note")

            if resolution_note:
                if resolution_note == "":
                    logs(f"No resolution note was generated by Ava for ticket ID# {id}")
                    pass

                else:
                    logs(f"Successfully generated resolution note for ticket ID# {id}")
                    put_resolution_note(ticket, str(resolution_note)) 

        else:
            logs(f"Failed to generate resolution note for ticket ID# {id}")
            
    else:
        logs(f"Failed to generate resolution note for ticket ID# {id}")

def check_ticket(ticket) -> str | None:
    current_res_notes = ticket.get("resolution_notes_html")

    if current_res_notes is None or current_res_notes == "":
        return

    else:
        return current_res_notes
